name: CMake

# activate tests for pull requests also
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Debug doesn't worry with optimizations -> reduces compile time
  BUILD_TYPE: Debug

jobs:
  build_and_test:
    # because the only thing the action is here for is to test on commits, ubuntu is really fine
    runs-on: ubuntu-latest

    steps:

    - name: Chechout
      uses: actions/checkout@v3

    - name: Configure
      run: make config 

    - name: Build
      run: make

    - name: Test
      run: make tests

